### ISSUE TITLE
BUG：二级菜单配置toc: false无效且内容不展示

### ISSUE THREAD

**Issue by chenxiong1032** [wx-open/wx-md-loader#1]
# 问题截图
## md文档
![image](https://user-images.githubusercontent.com/35932488/113821913-50775180-97af-11eb-871c-663d49e99a5e.png)
## 表现效果
![image](https://user-images.githubusercontent.com/35932488/113821961-61c05e00-97af-11eb-9526-6c84187107c6.png)

**Comment by chenxiong1032** [comment]
Please solve the problem as soon as possible

**Comment by ibreeze2017** [comment]
fixed at wx-api-docs @1.0.4
